---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: linkerd-viz
  namespace: linkerd-viz
spec:
  interval: 30m
  dependsOn:
    - name: linkerd-control-plane
      namespace: linkerd
  chart:
    spec:
      chart: linkerd-viz
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: linkerd-charts
        namespace: linkerd
  values:
    prometheus:
      enabled: false
    prometheusUrl: http://prometheus-operated.monitoring:9090/prometheus/
    grafana:
      externalUrl: http://localhost:8080/grafana/
    tap:
      externalSecret: true
      caBundle: |
        -----BEGIN CERTIFICATE-----
        MIIBjzCCATagAwIBAgIRAM0UVEYEnzvIZrZgDmr9kH0wCgYIKoZIzj0EAwIwJTEj
        MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwIBcNMjMxMjI4MTAw
        NzMxWhgPMjEyMzEyMDQxMDA3MzFaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5j
        bHVzdGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEHkeChI08vveJ
        hxyECpPGgL5qLVe9FQpQVkEfTM+OpHd/2fao9j5U7GyPhdSsz/DBtxeD0yKIJCT7
        JOsxoWnuAqNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEw
        HQYDVR0OBBYEFEajyyixJOFdt+OzPdrSdzRC3bYLMAoGCCqGSM49BAMCA0cAMEQC
        IBaYworY2Bf2EU+PhlAoZ8hWyMCP7zA9ULPuxe3g9bYaAiA9OaERGW1FwCDd5IKv
        EcJ4AJTIwRAowXpiU0db3tOniQ==
        -----END CERTIFICATE-----
    tapInjector:
      externalSecret: true
      caBundle: |
        -----BEGIN CERTIFICATE-----
        MIIBjzCCATagAwIBAgIRAM0UVEYEnzvIZrZgDmr9kH0wCgYIKoZIzj0EAwIwJTEj
        MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwIBcNMjMxMjI4MTAw
        NzMxWhgPMjEyMzEyMDQxMDA3MzFaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5j
        bHVzdGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEHkeChI08vveJ
        hxyECpPGgL5qLVe9FQpQVkEfTM+OpHd/2fao9j5U7GyPhdSsz/DBtxeD0yKIJCT7
        JOsxoWnuAqNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEw
        HQYDVR0OBBYEFEajyyixJOFdt+OzPdrSdzRC3bYLMAoGCCqGSM49BAMCA0cAMEQC
        IBaYworY2Bf2EU+PhlAoZ8hWyMCP7zA9ULPuxe3g9bYaAiA9OaERGW1FwCDd5IKv
        EcJ4AJTIwRAowXpiU0db3tOniQ==
        -----END CERTIFICATE-----
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkerd-viz
  namespace: linkerd-viz
  annotations:
    nginx.ingress.kubernetes.io/upstream-vhost: localhost:8084
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header Origin "";
      proxy_hide_header l5d-remote-ip;
      proxy_hide_header l5d-server-id;
spec:
  rules:
    # add this domain to your local hosts file binding to localhost
    - host: linkerd.localdomain
      http:
        paths:
          - backend:
              service:
                name: web
                port:
                  number: 8084
            path: /
            pathType: Prefix
