---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: linkerd-control-plane
  namespace: linkerd
spec:
  interval: 30m
  dependsOn:
    - name: linkerd-crds
  chart:
    spec:
      chart: linkerd-control-plane
      version: "~1"
      sourceRef:
        kind: HelmRepository
        name: linkerd-charts
        namespace: linkerd
  values:
    identity:
      # use CA certs from given configmap
      externalCA: true
      # causes the chart to skip the certificate secret creation, as we created the identity-issuer certificate secret beforehand
      issuer:
        scheme: kubernetes.io/tls
    proxyInjector:
      externalSecret: true
      caBundle: |
        -----BEGIN CERTIFICATE-----
        MIIBjzCCATagAwIBAgIRAM0UVEYEnzvIZrZgDmr9kH0wCgYIKoZIzj0EAwIwJTEj
        MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwIBcNMjMxMjI4MTAw
        NzMxWhgPMjEyMzEyMDQxMDA3MzFaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5j
        bHVzdGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEHkeChI08vveJ
        hxyECpPGgL5qLVe9FQpQVkEfTM+OpHd/2fao9j5U7GyPhdSsz/DBtxeD0yKIJCT7
        JOsxoWnuAqNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEw
        HQYDVR0OBBYEFEajyyixJOFdt+OzPdrSdzRC3bYLMAoGCCqGSM49BAMCA0cAMEQC
        IBaYworY2Bf2EU+PhlAoZ8hWyMCP7zA9ULPuxe3g9bYaAiA9OaERGW1FwCDd5IKv
        EcJ4AJTIwRAowXpiU0db3tOniQ==
        -----END CERTIFICATE-----
    profileValidator:
      externalSecret: true
      caBundle: |
        -----BEGIN CERTIFICATE-----
        MIIBjzCCATagAwIBAgIRAM0UVEYEnzvIZrZgDmr9kH0wCgYIKoZIzj0EAwIwJTEj
        MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwIBcNMjMxMjI4MTAw
        NzMxWhgPMjEyMzEyMDQxMDA3MzFaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5j
        bHVzdGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEHkeChI08vveJ
        hxyECpPGgL5qLVe9FQpQVkEfTM+OpHd/2fao9j5U7GyPhdSsz/DBtxeD0yKIJCT7
        JOsxoWnuAqNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEw
        HQYDVR0OBBYEFEajyyixJOFdt+OzPdrSdzRC3bYLMAoGCCqGSM49BAMCA0cAMEQC
        IBaYworY2Bf2EU+PhlAoZ8hWyMCP7zA9ULPuxe3g9bYaAiA9OaERGW1FwCDd5IKv
        EcJ4AJTIwRAowXpiU0db3tOniQ==
        -----END CERTIFICATE-----
    policyValidator:
      externalSecret: true
      caBundle: |
        -----BEGIN CERTIFICATE-----
        MIIBjzCCATagAwIBAgIRAM0UVEYEnzvIZrZgDmr9kH0wCgYIKoZIzj0EAwIwJTEj
        MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwIBcNMjMxMjI4MTAw
        NzMxWhgPMjEyMzEyMDQxMDA3MzFaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5j
        bHVzdGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEHkeChI08vveJ
        hxyECpPGgL5qLVe9FQpQVkEfTM+OpHd/2fao9j5U7GyPhdSsz/DBtxeD0yKIJCT7
        JOsxoWnuAqNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEw
        HQYDVR0OBBYEFEajyyixJOFdt+OzPdrSdzRC3bYLMAoGCCqGSM49BAMCA0cAMEQC
        IBaYworY2Bf2EU+PhlAoZ8hWyMCP7zA9ULPuxe3g9bYaAiA9OaERGW1FwCDd5IKv
        EcJ4AJTIwRAowXpiU0db3tOniQ==
        -----END CERTIFICATE-----
    podMonitor:
      enabled: true
