---
# https://github.com/linkerd/linkerd2/tree/main/charts
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: linkerd-charts
  namespace: linkerd
spec:
  interval: 120m
  url: https://helm.linkerd.io/stable
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: linkerd-smi-charts
  namespace: linkerd-smi
spec:
  interval: 120m
  url: https://linkerd.github.io/linkerd-smi

