---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: linkerd-cni
  namespace: linkerd
spec:
  interval: 30m
  dependsOn:
    - name: linkerd-crds
  chart:
    spec:
      chart: linkerd2-cni
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: linkerd-charts
        namespace: linkerd
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
