---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: ingress-controller
  namespace: monitoring
spec:
  namespaceSelector:
    matchNames:
      - ingress
  selector:
    matchLabels: {}
  podMetricsEndpoints:
    - interval: 10s
      port: metrics
