apiVersion: v1
data:
  ca-bundle.crt: |
    -----BEGIN CERTIFICATE-----
    MIIBjzCCATagAwIBAgIRAM0UVEYEnzvIZrZgDmr9kH0wCgYIKoZIzj0EAwIwJTEj
    MCEGA1UEAxMacm9vdC5saW5rZXJkLmNsdXN0ZXIubG9jYWwwIBcNMjMxMjI4MTAw
    NzMxWhgPMjEyMzEyMDQxMDA3MzFaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5j
    bHVzdGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEHkeChI08vveJ
    hxyECpPGgL5qLVe9FQpQVkEfTM+OpHd/2fao9j5U7GyPhdSsz/DBtxeD0yKIJCT7
    JOsxoWnuAqNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEw
    HQYDVR0OBBYEFEajyyixJOFdt+OzPdrSdzRC3bYLMAoGCCqGSM49BAMCA0cAMEQC
    IBaYworY2Bf2EU+PhlAoZ8hWyMCP7zA9ULPuxe3g9bYaAiA9OaERGW1FwCDd5IKv
    EcJ4AJTIwRAowXpiU0db3tOniQ==
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: linkerd-identity-trust-roots
  namespace: linkerd
