apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: examiner
  namespace: apps
spec:
  chart:
    spec:
      chart: application
      version: "~1"
      sourceRef:
        kind: HelmRepository
        name: chart-repo
        namespace: apps
      interval: 60m
  interval: 1m
  values:
    image:
      repository: quay.io/heubeck/examiner
      tag: latest
    linkerd:
      enabled: true
    monitoring:
      serviceMonitor: true
    configuration:
      ECHO_VALUE: ⛈ Canaries r0ck 🤘
      SERVER_ERROR_RATE: 0
      REQUEST_DELAY: 100..250
    canary:
      enabled: false
